version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_USER: nurs
      POSTGRES_PASSWORD: 4469
      POSTGRES_DB: localhost
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: go-app
      environment:
        DB_HOST: db
        DB_PORT: 5432
        DB_USER: nurs
        DB_PASSWORD: 4469
        DB_NAME: localhost
      ports:
        - "8000:8080"
      depends_on:
        - db
      volumes:
        - ../internal/db/migrations:/app/internal/db/migrations


volumes:
  pgdata:
