version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_USER: nurs
      POSTGRES_PASSWORD: 4469
      POSTGRES_DB: localhost
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
